server:
  port: 8081
  tomcat:
    max-threads: 1000
    accept-count: 1000

dubbo:
  application:
    ###########注册到注册中心的名称############
    name: consumer
  ###########采用协议和端口号################
  protocol:
    ###########采用dubbo协议####################
    name: dubbo
    ###########发布dubbo端口号为20880###########
    port: 20881
  registry:
    ###########注册中心地址#####################
    address: zookeeper://localhost:2181